//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabProj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class emploee_services
    {
        public int user_id { get; set; }
        public int service_id { get; set; }
    
        public virtual user user { get; set; }
    }
}
