//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabProj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class services_in_order
    {
        public int order_id { get; set; }
        public int service_id { get; set; }
        public int status { get; set; }
    
        public virtual order order { get; set; }
        public virtual service service { get; set; }
    }
}
